'use client';
import { useState, useEffect } from 'react';
import { log } from '@bluemetal/shared';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import Sidebar from '@/components/layout/Sidebar';
import api from '@/lib/api';
import { Camera, Circle, Maximize2, RefreshCw, Plus, X } from 'lucide-react';
import Hls, { ErrorData } from 'hls.js';
import { useRef } from 'react';

function HlsPlayer({ src, label }: { src: string; label: string }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    const video = videoRef.current;
    if (!video || !src) return;
    setError(false);

    if (Hls.isSupported()) {
      const hls = new Hls({ liveSyncDurationCount: 3 });
      hls.loadSource(src);
      hls.attachMedia(video);
      hls.on(Hls.Events.ERROR, (_: string, data: ErrorData) => {
        if (data.fatal) setError(true);
      });
      return () => hls.destroy();
    } else if (video.canPlayType('application/vnd.apple.mpegurl')) {
      video.src = src;
    } else {
      setError(true);
    }
  }, [src]);

  if (error) {
    return (
      <div style={{ width: '100%', height: '100%', background: '#111827', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
        <Camera size={32} className="text-gray-500" />
        <p className="text-gray-400 text-sm">Stream unavailable</p>
        <p className="text-gray-600 text-xs">{label}</p>
      </div>
    );
  }

  return (
    <video
      ref={videoRef}
      style={{ width: '100%', height: '100%', objectFit: 'cover' }}
      autoPlay
      muted
      playsInline
    />
  );
}

function StreamDot({ status }: { status: 'online' | 'offline' | 'unknown' }) {
  const color = status === 'online' ? 'text-green-400' : status === 'offline' ? 'text-red-400' : 'text-gray-400';
  return <Circle size={8} className={`${color} fill-current`} />;
}

function AddCameraModal({ onClose }: { onClose: () => void }) {
  const qc = useQueryClient();
  const [form, setForm] = useState({ name: '', location_label: '', rtsp_url: '', sort_order: 0 });

  const mutation = useMutation({
    mutationFn: () => api.post('/cameras', form).then(r => r.data),
    onSuccess: () => {
      toast.success('Camera added');
      qc.invalidateQueries({ queryKey: ['cameras'] });
      onClose();
    },
    onError: () => toast.error('Failed to add camera'),
  });

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', zIndex: 50, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16 }}>
      <div style={{ background: '#fff', borderRadius: 16, boxShadow: '0 25px 50px -12px rgba(0,0,0,0.25)', width: '100%', maxWidth: 448, padding: 24 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <h2 className="font-semibold text-[#1a3c5e]">Add Camera</h2>
          <button onClick={onClose}><X size={18} /></button>
        </div>
        <form onSubmit={e => { e.preventDefault(); mutation.mutate(); }} style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <div>
            <label className="label">Camera Name *</label>
            <input required value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} className="input" placeholder="e.g. Entrance Gate" />
          </div>
          <div>
            <label className="label">Location Label</label>
            <input value={form.location_label} onChange={e => setForm(f => ({ ...f, location_label: e.target.value }))} className="input" placeholder="e.g. Main Plant" />
          </div>
          <div>
            <label className="label">RTSP URL *</label>
            <input required value={form.rtsp_url} onChange={e => setForm(f => ({ ...f, rtsp_url: e.target.value }))} className="input" placeholder="rtsp://192.168.1.x:554/stream" />
          </div>
          <div>
            <label className="label">Sort Order</label>
            <input type="number" value={form.sort_order} onChange={e => setForm(f => ({ ...f, sort_order: Number(e.target.value) }))} className="input" min="0" />
          </div>
          <p className="text-xs text-gray-400">The HLS stream URL is automatically generated by the MediaMTX pipeline.</p>
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, paddingTop: 8 }}>
            <button type="button" onClick={onClose} style={{ padding: '8px 16px' }} className="text-sm border rounded-lg">Cancel</button>
            <button type="submit" disabled={mutation.isPending} style={{ padding: '8px 16px' }} className="text-sm bg-[#1a3c5e] text-white rounded-lg disabled:opacity-60">
              {mutation.isPending ? 'Adding…' : 'Add Camera'}
            </button>
          </div>
        </form>
      </div>
      <style jsx global>{`
        .label { display:block; font-size:.75rem; font-weight:500; color:#4b5563; margin-bottom:4px; }
        .input { width:100%; border:1px solid #d1d5db; border-radius:8px; padding:8px 12px; font-size:.875rem; outline:none; }
        .input:focus { border-color:#1a3c5e; }
      `}</style>
    </div>
  );
}

export default function CamerasPage() {
  useEffect(() => { log.page('Cameras'); }, []);
  const [cols, setCols] = useState<2 | 3 | 4>(3);
  const [fullscreen, setFullscreen] = useState<string | null>(null);
  const [showAdd, setShowAdd] = useState(false);

  const { data: cameras = [] } = useQuery({
    queryKey: ['cameras'],
    queryFn: () => api.get('/cameras').then(r => r.data),
  });

  const { data: health = [], refetch: refetchHealth } = useQuery({
    queryKey: ['cam-health'],
    queryFn: () => api.get('/cameras/health').then(r => r.data),
    refetchInterval: 30000,
  });

  const healthMap = Object.fromEntries((health as any[]).map((h: any) => [h.cameraId, h.status]));

  const fullscreenCam = (cameras as any[]).find((c: any) => c.id === fullscreen);

  return (
    <div style={{ display: 'flex' }}>
      <Sidebar />
      <main style={{ flex: 1, padding: 32 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
          <div>
            <h1 className="text-2xl font-bold text-[#1a3c5e]">Live Cameras</h1>
            <p className="text-sm text-gray-500 mt-0.5">RTSP → HLS via MediaMTX · refreshes every 30s</p>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ display: 'flex', overflow: 'hidden' }} className="border border-gray-200 rounded-lg">
              {([2, 3, 4] as const).map(n => (
                <button key={n} onClick={() => setCols(n)} className={`px-3 py-1.5 text-sm font-medium transition-colors ${cols === n ? 'bg-[#1a3c5e] text-white' : 'text-gray-600 hover:bg-gray-50'}`}>
                  {n}×
                </button>
              ))}
            </div>
            <button onClick={() => refetchHealth()} className="p-2 text-gray-500 hover:text-gray-700 border border-gray-200 rounded-lg">
              <RefreshCw size={16} />
            </button>
            <button onClick={() => setShowAdd(true)} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 16px' }} className="bg-[#1a3c5e] text-white rounded-lg text-sm font-medium hover:bg-[#2563a8]">
              <Plus size={16} /> Add Camera
            </button>
          </div>
        </div>

        {(cameras as any[]).length === 0 ? (
          <div style={{ textAlign: 'center', paddingTop: 80, paddingBottom: 80 }} className="text-gray-400">
            <Camera size={48} style={{ margin: '0 auto 12px' }} className="opacity-30" />
            <p className="text-lg font-medium">No cameras configured</p>
            <p className="text-sm mt-1">Click "Add Camera" to register your first CCTV stream.</p>
          </div>
        ) : (
          <div style={{ display: 'grid', gap: 12, gridTemplateColumns: `repeat(${cols}, 1fr)` }}>
            {(cameras as any[]).map((cam: any) => {
              const status = healthMap[cam.id] || 'unknown';
              return (
                <div key={cam.id} className="bg-gray-900 rounded-xl group" style={{ aspectRatio: '16/9', overflow: 'hidden', position: 'relative' }}>
                  {cam.hls_url ? (
                    <HlsPlayer src={cam.hls_url} label={cam.name} />
                  ) : (
                    <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
                      <Camera size={28} className="text-gray-600" />
                      <p className="text-gray-500 text-xs">HLS not ready</p>
                    </div>
                  )}

                  {/* Overlay */}
                  <div style={{ position: 'absolute', inset: 0 }} className="bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity">
                    <div style={{ position: 'absolute', top: 8, right: 8 }}>
                      <button onClick={() => setFullscreen(cam.id)} className="bg-black/50 text-white p-1.5 rounded-lg">
                        <Maximize2 size={14} />
                      </button>
                    </div>
                  </div>

                  {/* Label bar */}
                  <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, padding: '8px 12px' }} className="bg-gradient-to-t from-black/80 to-transparent">
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                      <StreamDot status={status} />
                      <span className="text-white text-xs font-medium truncate">{cam.name}</span>
                      {cam.location_label && <span className="text-gray-300 text-xs truncate">· {cam.location_label}</span>}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </main>

      {/* Fullscreen modal */}
      {fullscreenCam && (
        <div style={{ position: 'fixed', inset: 0, background: '#000', zIndex: 50, display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 16px' }} className="bg-black/80">
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <StreamDot status={healthMap[fullscreenCam.id] || 'unknown'} />
              <span className="text-white font-medium">{fullscreenCam.name}</span>
              {fullscreenCam.location_label && <span className="text-gray-400 text-sm">· {fullscreenCam.location_label}</span>}
            </div>
            <button onClick={() => setFullscreen(null)} className="text-white p-2"><X size={20} /></button>
          </div>
          <div style={{ flex: 1 }}>
            {fullscreenCam.hls_url
              ? <HlsPlayer src={fullscreenCam.hls_url} label={fullscreenCam.name} />
              : <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }} className="text-gray-500">Stream not ready</div>
            }
          </div>
        </div>
      )}

      {showAdd && <AddCameraModal onClose={() => setShowAdd(false)} />}
    </div>
  );
}
